instrumentation:
    include-all-sources: true
    excludes:
        - 'public/**'
        - 'components/**/script.js'
        - 'all.js'
check:
    global:
        statements: 90
        branches: 84
        functions: 96
        lines: 94
