instrumentation:
    include-all-sources: true
    excludes:
        - 'public/**'
        - 'assets/**'
        - 'components/**'
check:
    global:
        statements: 0
        branches: 0
        functions: 0
        lines: 0
