instrumentation:
    include-all-sources: true
    excludes:
        - 'public/**'
        - 'assets/**'
        - 'components/**'
check:
    global:
        statements: 90
        branches: 84
        functions: 96
        lines: 94
